const OPEN_STATUSES = ['PENDING', 'ACTIVE', 'EXTENDED', 'OVERDUE', 'EXTENSION_REQUESTED'];
const TASK_STATUSES = [...OPEN_STATUSES, 'COMPLETED', 'CANCELLED'];
const PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
const COMPLETION_RESULTS = ['ON_TIME', 'WITHIN_EXTENSION', 'LATE'];
const USER_FIELDS = 'name username';

module.exports = { OPEN_STATUSES, TASK_STATUSES, PRIORITIES, COMPLETION_RESULTS, USER_FIELDS };
